### ISSUE TITLE
Learning from pixels and tic-tac-toe

### ISSUE THREAD

**Issue by mohanr** [nproellochs/ReinforcementLearning#1]
Searched for a link to post a comment in your blog..
I am a beginner but have coded the tic-tac-toe in Haskell based on Sutton's Lisp code. The RL agent wins more than 50% of the time but the  algorithm does not converge in that the RL agent does not consistently win 80-90 % of the time. It wavers probably because my haskell has a hidden bug.

But my main question is this. Do you need so many ( 406,541 )samples to make the RL agent consistently win 80-90 % of the time ?

And the other main question is this. Does the package let me save frames of a video of a game board to let the RL agent learn ? OpenCV can be used to pipe the pixel frames. I think.

**Comment by nproellochs** [comment]
1) Theoretically, the RL policy should also converge with less samples.

2) The ReinforcementLearning package learns an optimal policy from a fixed set of a priori known transition samples. Hence, you must use another tool to save the frames from the video. In a next step, you can load the images to R and transform them into RL states (see package documentation). However, there might be some performance issues with that many states.
