### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by mg64ve** [nproellochs/ReinforcementLearning#10]
Hello,

nice package, thanks for making it available.
Do you have other examples, with more states or more complex?
I am quite new to Q-Learning and more examples would be very beneficial.

Thanks.
Regards.

**Comment by nproellochs** [comment]
Hi mg64ve,

Additional working examples are now available as part of the package vignette.

Kind regards,
Nicolas

**Comment by mg64ve** [comment]
Thanks @nproellochs I will have a look.
