### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by Anis-Hoayek** [nproellochs/ReinforcementLearning#13]
I have an issue in the package dealing with Reinforcement Learning in R.
I learned the package based on the document published on the following link : 

https://cran.r-project.org/web/packages/ReinforcementLearning/vignettes/ReinforcementLearning.html

The problem is the following: after performing a reinforcement learning on the “TIC TAC TOE” data (as suggested by the authors), I tried to use the model to predict the next action of the following state “"XBXBB..X." ("B" for 0 and "." for empty cases in a TIC TAC TOE game)
Logically the best next action should be “c6” (case 6), however the model is suggesting “c1” which is totally illogical because case “c1” has already an input "X".
I will be thankful if someone may explain this strange situation.

Regards,
Anis Hoayek

**Comment by nproellochs** [comment]
Dear Anis,
Thank you for raising this issue. There seems to be nothing wrong with the code / learning setup. Apparently, the "tictactoe" dataset is limited in the sense that it does not contain the states "XBXBBB.XX" and "XBXBB.XX."  - i.e. the situations in which the agent loses the game if not choosing "c6." In other words, the "tictactoe" only contains a subset of all possible game situations; extending the dataset should allow the agent to learn the (real-world) solution for the game situation you're describing. I will consider adding an extended "tictactoe" dataset as part of the next package version.
Best,
Nicolas
