### ISSUE TITLE
Simulating behavior and calculating optimal solutions for n-armed bandits

### ISSUE THREAD

**Issue by ndphillips** [nproellochs/ReinforcementLearning#2]
I'd like to use your package to simulate behavior (using different learning and choice algorithms), and calculate optimal choice behavior for bandit tasks. Is this possible using your package? If so, do you have examples or tutorials that demonstrate best practices for doing this? Thanks! (Tagging @RichieRocks who will also be interested)

**Comment by nproellochs** [comment]
You can use the package to set up an environment function that simulates the dynamics of the environment (see package vignette for details). In addition, you can specify the learning parameters of the q-learning agent (learning rate, exploration parameter, discount factor).
