### ISSUE TITLE
Partial information situations

### ISSUE THREAD

**Issue by yipcma** [nproellochs/ReinforcementLearning#3]
I'm curious if the methods in this package could also deal with states where certain information or not observed (such as in a card game)?

Specifically, how should one construct the state, action, reward,next_s in such a situation?

Thank you very much in advance.

**Comment by nproellochs** [comment]
Thanks for your interest in the package. You can use the package to set up an environment function that simulates the dynamics of the environment (i.e. the card came). Let's think about a poker game: Here, a state would be given by the pocket cards and the community cards. The action set could be: raise, fold, or call. The agent would then receive a positive reward if he wins the game and a negative reward in all other cases.
