### ISSUE TITLE
Function does not work with data "tbl_df" "tbl" "data.frame"

### ISSUE THREAD

**Issue by vzhomeexperiments** [nproellochs/ReinforcementLearning#5]
Hi,

I experienced error while trying to use function ReinforcementLearning. 

> Error in ReinforcementLearning(DF2, s = "State", a = "Action", r = "Reward",  : 
>   Input data invalid. States and actions must be of type 'character', while rewards must be of type 'numeric'.

Checking columns of my data the result was TRUE
```
is.character(DF2$State)
is.character(DF2$Action)
is.numeric(DF2$Reward)
is.character(DF2$NextState)
```
Apparently dataframe was generated with dplyr functions so `class(DF2)` was "tbl_df" "tbl" "data.frame"

I could solve this problem by changing class of the object to data.frame
`DF2 <- as.data.frame.data.frame(DF2)`

Perhaps this info will be of help...
Thank you!

**Comment by nproellochs** [comment]
Many thanks for your feedback. The issue will be fixed in the next version of the package.
