### ISSUE TITLE
Error when Rewards contain NA

### ISSUE THREAD

**Issue by ff137** [nproellochs/ReinforcementLearning#6]
Hello - thank you for your work in creating this package.

I was struggling for a while with the following unclear error when running ReinforcementLearning on a dataset:
`Error in colnames(x)[apply(x, 1, which.max)] : invalid subscript type 'list'`

After some debugging I found that it's thanks to the dataset Reward column containing some NAs. So just reporting that it may be helpful to add a check that reports that before the model runs.

All the best

**Comment by nproellochs** [comment]
Hi mdebeer,

Thank you for your feedback and interest in the package. The issue will be fixed in the next package version.

Best,
Nicolas

**Comment by nproellochs** [comment]
Fixed.
