### ISSUE TITLE
Recommendation 

### ISSUE THREAD

**Issue by vzhomeexperiments** [nproellochs/ReinforcementLearning#8]
Hi Nicolas,

Thanks for writing this package!

In order to let Reinforcement Learning function to successfully generate policy even if there is only one new observation is generated I recommend to add into the function a dummy data generator with 0 rewards, perhaps as an option. 

`  d_tupple <- data.frame(State = states,
                         Action = rep(actions,length(states)),
                         Reward = rep(0,length(states)),
                         NextState = states,
                         stringsAsFactors = F)`

Example of practical implementation is [here](https://github.com/vzhomeexperiments/R_tradecontrol/blob/master/TEST5/generate_RL_policy.R)

test data to the function is [here](https://github.com/vzhomeexperiments/R_tradecontrol/blob/master/test_data/data_trades_markettype.rds)

Sorry I am not [yet] capable to create pull requests and develop packages... hope this info would help!

Best,
Vlad

**Comment by nproellochs** [comment]
Thank you the valuable suggestion, Vlad! I will definitely consider this as an additional feature for the next package version.

Best,
Nicolas
