### ISSUE TITLE
policy iteration

### ISSUE THREAD

**Issue by salma-daoud** [nproellochs/ReinforcementLearning#9]
Hello Nicolas,

Thanks for writing this package!

Once I have RL in production mode using my final policy. Can I iterate the policy each time I have new data to learn form this iteration?

thanks

**Comment by nproellochs** [comment]
Hi Salma-daoud,

Thank you for using the package. You can update the policy using ReinforcementLearning(data,existingModel). A toy example is provided in our arXiv paper on Reinforcement Learning in R (https://arxiv.org/pdf/1810.00240.pdf).

Best,
Nicolas

**Comment by salma-daoud** [comment]
Hi,
Thank you for your reply. I like your article : well written and very clear.
My issue is more specific:
 So let say that trained the system using sampleExperience data and found a policy1 then updated the policy using the new data from sampleExperience with the model found to get policy2. 
however this new policy "policy2" is not the optimal because I don't have all data (rewards)
Now I want to use the policy2 a real system using "predict(model, data_unseen$State)" and then use this new " unseen data " to update the system automaticaly by updating the policy2 for each iteration.

Is this possible using your pakage?

Thank you!

**Comment by nproellochs** [comment]
Hi salma-daoud,

For the latter, I would suggest to iteratively update the policy based 
on the newly generated experience (e.g. by using RL(newData) in a for 
loop). Alternatively, you can specify a custom function that specifies 
the dynamics of the environment (see package manual for details).

Best,

Nicolas

**Comment by salma-daoud** [comment]
Thank you very much for your help!
if I may I ask, how to manage final states here. In fact, my final  result should be a sequence of actions (best combination) from an initial state to the final state.
